sudo: required
services:
  - docker

before_install:
  - docker build -t anandahlawat/multi-docker-test -f ./client/Dockerfile.dev .

script:
  - echo "no tests!"

after_success:
  - docker build -t anandahlawat/multi-client ./client
  - docker build -t anandahlawat/multi-ningx ./nginx
  - docker build -t anandahlawat/multi-server ./server
  - docker build -t anandahlawat/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER_NAME" --password-stdin
