sudo: required
services:
  - docker

before_install:
  - docker build -t anandahlawat/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - echo "no tests!"

after_success:
  - docker build -t anandahlawat/multi-client ./client
  - docker build -t anandahlawat/multi-ningx ./nginx
  - docker build -t anandahlawat/multi-server ./server
  - docker build -t anandahlawat/multi-worker ./worker

  - echo "$dockerpassword" | docker login -u "$dockeruname" --password-stdin
  - docker push anandahlawat/multi-client:latest
  - docker push anandahlawat/multi-ningx:latest
  - docker push anandahlawat/multi-server:latest
  - docker push anandahlawat/multi-worker:latest
